/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.chatter.platform;

import com.chatter.platform.commands.*;
import com.chatter.platform.services.UserService;
import com.chatter.platform.services.ChatRoomService;
import com.chatter.platform.utils.Constants;

import java.util.Scanner;

public class App {

        public static void main(String[] args) {
            UserService userService = new UserService();
            ChatRoomService chatRoomService = new ChatRoomService();
            Scanner scanner = new Scanner(System.in);

            while (true) {
                String input = scanner.nextLine().trim();
                String[] parts = input.split(" ");

                if (parts.length == 0) {
                    System.out.println(Constants.REQUEST_PATTERN_INVALID);
                    continue;
                }

                String commandStr = parts[0].toUpperCase();
                Command command;
                switch (commandStr) {
                    case Constants.REGISTER:
                        command = new RegisterCommand(userService);
                        break;
                    case Constants.LOGIN:
                        command = new LoginCommand(userService);
                        break;
                    case Constants.LOGOUT:
                        command = new LogoutCommand(userService, chatRoomService);
                        break;
                    case Constants.CREATE_ROOM:
                        command = new CreateRoomCommand(chatRoomService);
                        break;
                    case Constants.ADD:
                        command = new AddUserCommand(userService, chatRoomService);
                        break;
                    case Constants.USER_DETAIL:
                        command = new UserDetailCommand(userService, chatRoomService);
                        break;
                    case Constants.LISTROOMS:
                        command = new ListRoomsCommand(chatRoomService);
                        break;
                    case Constants.EXIT:
                        command = new ExitCommand(userService, chatRoomService);
                        break;
                    default:
                        System.out.println(Constants.REQUEST_PATTERN_INVALID);
                        continue;
                }

                String result = command.execute(parts);
                System.out.println(result);

                if (commandStr.equals(Constants.EXIT)) {
                    break;
                }
            }

            scanner.close();
        }

}
