/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.krimsonkourses.platform;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        CommandHandler commandHandler = new CommandHandler();
        Scanner scanner = new Scanner(System.in);

        while (true) {
            String command = scanner.nextLine().trim();
            String result = commandHandler.handleCommand(command);
            System.out.println(result);

            if (command.equals("EXIT")) {
                break;
            }
        }

        scanner.close();
    }
}
