/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package section2;

import section2.level1.Artist;
import section2.level1.Song;
import section2.level2.Car;
import section2.level2.workshop.Mechanical;

public class App {
    public static void main(String[] args) {
        Song song = new Song();
        song.name = "Love Story";
        song.artist = "Taylor Swift";
        song.id = 12;

        Artist artist = new Artist(1, "Imagine Dragons", "USA");

        Car car = new Car("Civic","Honda",4,20);
        Mechanical mechanical = new Mechanical();
        mechanical.paint(car);
        Mechanical.addTyres(car);

    }
}
